### PR TITLE
try more dedicated icon for sign maker

### PR DESCRIPTION
**Pull request by matkoniecz**
see #41

### CODE REVIEW

**Comment by matkoniecz** [comment]
Sadly, it has not worked. Not sure why.

**Comment by matkoniecz** [comment]
screen

**Comment by matkoniecz** [comment]
Thanks so much for the fix!

**Comment by tyrasd** [comment]
I'm wondering whether https://fontawesome.com/v5/icons/sign?f=classic&s=solid would be even more fitting?

**Comment by matkoniecz** [comment]
yes, seems better as it is far more likely that they will make one looking like this

**Pull request merged**
