### PR TITLE
Added website/email/phone to apartment presets

### PR DESCRIPTION
**Pull request by rene78**

### CODE REVIEW

**Review by tyrasd — COMMENTED** [review]
Is there a particular reason why apartments should always show these fields? FWIW, even the hotel preset has these fields as `moreFields`. :eyes:

**Review by tyrasd — APPROVED** [review]
Ah, I didn't see your other PR #306 yet.

Ok, I think the contact information is quite important and useful for touristic accommodations. But then we should also change this for the other accommodation features like `tourism=chalet`, or `tourism=guest_house`.

**Comment by tyrasd** [comment]
merged as d7d01f8e97bf421bf67029223edaddadeccec445

**Comment by rene78** [comment]
> ...we should also change this for the other accommodation features like `tourism=chalet`, or `tourism=guest_house`.

Gonna look into it.

**Comment by tyrasd** [comment]
did you see commit d7d01f8e97bf421bf67029223edaddadeccec445 ? There, I already added the fields to the other accommodation types.

**Comment by rene78** [comment]
Yes, saw it after writing the message above. Thanks!

**Pull request closed without merging**
