### PR TITLE
Create gynaecology.json

### PR DESCRIPTION
**Pull request by rene78**
Preset for a Gynaecologist added

### CODE REVIEW

**Comment by kjonosm** [comment]
Could you double check the synonyms you have picked?
Fertility treatment facilities seem to have their own specialty tag `healthcare:speciality=fertility`.
See also https://wiki.openstreetmap.org/wiki/Key:healthcare#Specialities_for_other_medical_facilities

**Comment by kjonosm** [comment]
Could you also add "gynecology", "gynecologist" and "women's doctor" as synonyms?

**Comment by rene78** [comment]
> Could you also add "gynecology", "gynecologist" and "women's doctor" as synonyms?

Synonyms are aliases, I suppose? Like that?

```
    "aliases": [
        "Gynecology",
        "Gynecologist",
        "Women's doctor"
    ]
```

**Comment by kjonosm** [comment]
Sorry @rene78 , I meant synonyms as in additional "terms"

**Comment by rene78** [comment]
> Sorry @rene78 , I meant synonyms as in additional "terms"

Done. Thanks for the hint.

**Pull request merged**
