### PR TITLE
Update derail.json

### PR DESCRIPTION
**Pull request by ZEE6de**
expand

### CODE REVIEW

**Comment by mbrzakovic** [comment]
I can confirm that these fields do have significant usage when combined with railway:derail.
Some stats from taginfo:
railway=derail  ~9k
combination with railway:derail=*  ~3k
combination with railway:local_operated=* ~3k

Unfortunately, I can't seem to find any official documentation for these keys  (non-existent wiki pages for fields and not mentioned in [derail](https://wiki.openstreetmap.org/wiki/Tag:railway=derail)). There is some good information on [open railway map wiki](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Derailers.2C_Trap_Points.2C_Catch_Points) however I can't really say if this is sufficient to integrate these in the tagging schema.

It would be great to hear some more opinions on this.

Connected (prerequisites): #180, #181

**Review by tyrasd — CHANGES_REQUESTED** [review]
Please include the changes of the other files from #180 and #181 in this PR. If you need help using github to create a PR which includes multiple files, you might find some help in this [stackoverflow thread](https://stackoverflow.com/questions/17815895/can-i-edit-two-files-then-make-one-commit-using-github-web-based-editor). If you're still stuck, please ask.

**Comment by tyrasd** [comment]
> expand

could you please expand the description of this pull request? :stuck_out_tongue_closed_eyes:

**Comment by tyrasd** [comment]
> Unfortunately, I can't seem to find any official documentation for these keys

That's a pity. I would refrain from merging this if there really is no documentation about these tags at all in the wiki. Perhaps @ZEE6de – do you know the place where these tags are discussed or documented?

**Comment by matkoniecz** [comment]
Also, if this tags are in use - would you be willing to create documentation for them?

Then see https://wiki.openstreetmap.org/wiki/Creating_a_page_describing_key_or_value - feel free to ask for help here (hopefully that is OK) or on https://wiki.openstreetmap.org/wiki/Talk:Wiki

**Pull request closed without merging**
