### PR TITLE
Add presets for `highway=path`-based cycle-footway tagging

### LINKED ISSUE #109: New preset: Cycle & Foot Path for Europe
We already have Cycle & Foot Path, but for US and UK, where tagging is different.
Please add also a preset for other countries: France, Lithuania, Poland where we use
```
highway=path
foot=designated
bicycle=designated

segregated = yes/no
```

### LINKED ISSUE #267: Add regional presets for german cycleway tagging
I am thinking about adding regional presets for cycleways in Germany … – Any thoughts on this? Would such a PR be merged?

Presets I am considering:

- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:240
    See https://github.com/openstreetmap/id-tagging-schema/pull/345
- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:241-30
- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:241-31
- [ ] "Fahrradstraße" https://wiki.openstreetmap.org/wiki/DE:Key:bicycle_road with traffic_sign=DE:244.1 ([Example](https://www.openstreetmap.org/way/744158640)) ==> https://github.com/openstreetmap/id-tagging-schema/pull/1207

They describe very specific tagging for footways with access rules for bikes.

The traffic sign could be part of the icon and also added as part of the preset.

I think having a clear name in iD (…) for a way with this tagging would be helpful.

---

**Notes about regional presets:**

(Thanks to [a comment by Bryan](https://github.com/openstreetmap/id-tagging-schema/pull/288#issuecomment-986919641))

Presets and fields support a `locationSet` to include/exclude countries.
- `locationSet: { include: ["de"] }`
- `locationSet: { exclude: ["de"] }`

The code in iD (https://github.com/openstreetmap/iD/pull/8305/files#diff-f38480d9980a09d7046b627edd05069ed2b53e545697888c66b697e855b8d886R10-R22) uses the location-conflation module https://github.com/ideditor/location-conflation#what-is-it which in turn allows uses country-coder https://github.com/ideditor/country-coder#what-is-it which allows all kinds of regional identifiers.

Quick link to a search result list of presets and fields that use this feature right now: https://github.com/openstreetmap/id-tagging-schema/search?q=locationSet

### LINKED ISSUE #317: Preset for a way designated for both cyclists and pedestrians, without separate spaces (segregated=no)
There seems to be missing a preset for case **S7** in https://wiki.openstreetmap.org/wiki/Bicycle#Miscellaneous

so a combination of tags:
```
highway=footway/highway=cycleway/highway=path
+ bicycle=designated
+ foot=designated
+ segregated=no
```
I think main tag: highway=path would be the most universal for a preset.

Fields can be the same as for cycleway or footway.

This type of footway shared with bicycles is (unfortunately) very popular in Poland and it would be good to have a preset corresponding to that so new mappers aren't confused about mapping those.

### LINKED ISSUE #759: Cycle & Foot Path preset missing from search results in France
**Describe the bug**

When searching for presets for cycle tracks in France using the search string "cycle &" the presets Cycle & Foot Crossing and Cycle & Foot Path do not show up in the presets list whereas in the UK the same search produces those presets as part of the results. Such paths occur both in the UK and France as the presets cover both segregated and unsegregated versions of such paths.

**To Reproduce**

Search for presets using the search string "cycle &" when over an area of France.

**Expected behavior**

Presets Cycle & Foot Crossing and Cycle & Foot Path showing up in the search results.

**Screenshots**

image

### LINKED ISSUE #1205: Add `highway=path+bicycle=designated` as regional preset(?)
We have the `bicycle_foot.json` presets (https://github.com/search?q=repo%3Aopenstreetmap%2Fid-tagging-schema+bicycle_foot.json&type=code) that allow to search for a "Cycle & Foot Path" and use the tagging `highway=cycleway +         foot=designated + bicycle=designated`.

Those presets are only active in some regions (see `locationSet.exclude`).

https://github.com/openstreetmap/id-tagging-schema/pull/1044/files#diff-a834664ac0cff3853300a80fc424c63679502e50a1a7894067b2eb2ffd3b6503R2 suggest to expand on this schema to add the remaining crossing cases to this setup.

https://github.com/openstreetmap/id-tagging-schema/pull/1201 suggest to add (un-searchable) `highway=path` crossing presets that are named "Cycle & Foot Crossing".

Looking at the situation in Germany, we are missing a searchable preset for highway=path as a designated bike + foot infrastructure. This is the same idea that the `bicycle_foot` have but the local community prefers `highway=path` instead of `highway=cycleway`. 

https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:240 describes such a signed infrastructure and references both tags (`path` and `cycleway`) as possible highway classes (with a preference for `path`).

What would be the best way to solve this for this schema?

- We could expand the schema with https://github.com/ideditor/schema-builder/issues/150 and make those presets unsearchable/searchable in certain regions. That would be ideal, because we don't have to duplicate presets.
- We could duplicate presets and make them unsearchable in those regions that prefer a different tagging style. That would improve the situation in a way that it makes the data visible but still has a clear recommendation for one tagging schema (in a given region).
- We could leave it as is on the premise that users know about access tagging (how to add and how to read it) in order to fully interpret the given infrastructure.

### PR DESCRIPTION
**Pull request by olafkryus**
### Description, Motivation & Context

Some of the regions are opted out of the cycle-footway preset currently available in iD, since the preset insists on using the `highway=cycleway` tag, but those communities accepted the use of `highway=path` tag as their consensus on tagging the feature. Yet no alternative preset is available, therefore in these regions, those cycle-footways are displayed in iD in same way as regular path, with no way to apply any preset, neither `cycleway` nor `path`-based one. This PR aims to fill the gap.

### Related issues

* Closes #109
* Partially overlaps with #267
* Partially overlaps with #317
* Closes #759
* Partially overlaps with #1193
* Partially overlaps with #1205

### CODE REVIEW

**Comment by matkoniecz** [comment]
> Partially resolves 

will it cause github to close linked issue? maybe put "resolves (partially)" ?

**Comment by tordans** [comment]
FYI: There is a big refactoring on crossings as a PR that I am waiting for to be merged for a long while now.

**Comment by tordans** [comment]
> FYI: There is a big refactoring on crossings as a PR that I am waiting for to be merged for a long while now.

FYI this was merged recently. Could you rebase your PR?

**Comment by olafkryus** [comment]
>> Partially resolves
>
> will it cause github to close linked issue? maybe put "resolves (partially)" ?

@matkoniecz Actually yes it would, which we do not want, thanks for pointing that out. Reworded to "Partially overlaps with" so it won't happen.


> FYI: There is a big refactoring on crossings as a PR that I am waiting for to be merged for a long while now.

> FYI this was merged recently. Could you rebase your PR?

@tordans Done.

**Comment by olafkryus** [comment]
I've also now added Norway to the inclusion/exclusion country lists in the modified presets, as per #1193, since that's basically the same issue, which seems to have been "forgotten" for some reason? :man_shrugging:

**Comment by tordans** [comment]
@olafkryus please use the test template to add some test cases to this PR https://github.com/openstreetmap/id-tagging-schema/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L24-L70

I also commented on https://github.com/openstreetmap/id-tagging-schema/pull/1193#issuecomment-2553205701 and you might have an opinion on this.

TBH I am not sure that adding the regional preset changes to this PR will lead to this one being merged sooner. It might be better to keep those things separated.

**Comment by tordans** [comment]
@olafkryus 
> TBH I am not sure that adding the regional preset changes to this PR will lead to this one being merged sooner. It might be better to keep those things separated.

Given how the conversation went in https://github.com/openstreetmap/id-tagging-schema/pull/1193 I would like to tune back this PR to only include the added preset (and maybe the missing "de" https://github.com/openstreetmap/id-tagging-schema/pull/1384/files#diff-3b8f616654b5d2845f63eb05ce32b27741d3945ad0a71e55033de12a656d8b56R7)

I would consider this ready for merge then. But we still should [check the test checklist first](https://github.com/openstreetmap/id-tagging-schema/pull/1384#issuecomment-2553220207).

**Comment by olafkryus** [comment]
## Test-Documentation

### Preview links & Sidebar Screenshots

Icons are copied, and fields are directly re-used from already existing related `highway=cycleway`-based tagging presets.

#### Bicycle & Foot Path
https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#background=Geoportal2-PL-aerial_image_WMTS&disable_features=boundaries&id=w991414746&locale=en&map=20.22/50.26270/19.00850
obraz
#### Bicycle & Foot Crossing
https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#background=Geoportal2-PL-aerial_image_WMTS&disable_features=boundaries&id=w699046787&locale=en&map=20.22/50.26270/19.00850
obraz

### Search
obraz
obraz

### Info-`i`
#### Bicycle & Foot Path
obraz
#### Bicycle & Foot Crossing
obraz

### Wording

New presets directly re-use all wording from already existing related `highway=cycleway`-based tagging presets.

**Comment by olafkryus** [comment]
@tordans If I had paid a bit more attention to the description of #1193, I probably would have noticed that it's similarly-looking solution is actually an unexpected method of trying to solve a bit different problem. 🫥 Whether cycleway is implying bicycle designation is quite a good point, but certainly for another issue. (on the bright side, at least that moved forward a bit :wink: ). For now, it's Norway-out from the country lists here.

Test Documentation added.

**Comment by tordans** [comment]
It's great to have this in place, now. Looking at it on the map makes me hope we will find a good solution for  https://github.com/openstreetmap/iD/pull/10256 which would resolve the rendering issue of those shared path lines. — Maybe you have an idea over there.

**Comment by tordans** [comment]
Documentation:

The _info-i_ part is a bit unfortunate but I don't see any way to reference a wiki page that will show something with a more to the point meaning. It is all very generic `hw=path` and not what we would want to see here like "shared bike and pedestrian path/crossing, segregated or not".

When I switch from a shared path to a cycle path and back via presets the "segregated=*" value gets lost. But I think that is OK for this use case.

Search looks good image

**Review by tordans — APPROVED** [review]

**Comment by 1ec5** [comment]
> The info-i part is a bit unfortunate but I don't see any way to reference a wiki page that will show something with a more to the point meaning. It is all very generic hw=path and not what we would want to see here like "shared bike and pedestrian path/crossing, segregated or not".

That’s a known issue with the tagging scheme overall. I’m not sure we can reasonably expect a single brief description that covers the tag’s multiple personalities. There are too many relevant forum threads to list here, but here are a few off the top of my head:

* [RfC: Reorder samples in highway=path documentation](https://community.openstreetmap.org/t/rfc-reorder-samples-in-highway-path-documentation/122783)
* [Request for Comments: Solution proposal for the `path` issues](https://community.openstreetmap.org/t/request-for-comments-solution-proposal-for-the-path-issues/122660)
* [Documenting the problems with `highway=path`](https://community.openstreetmap.org/t/documenting-the-problems-with-highway-path/119103)
* [Mapping combined ways for cycling and walking](https://community.openstreetmap.org/t/mapping-combined-ways-for-cycling-and-walking/119404)

**Comment by tordans** [comment]
@1ec5 I was thinking along the lines of …
- find a way to model a wiki data item for a tag combination and use that as reference for a preset –> AFAIK that is not part of the wiki data item setup at this point
- have an optional hard coded info-i text here in the code –> this could get messy and would move more responsibility here which I don't think is worth the effort at this point

The [reference](https://github.com/ideditor/schema-builder?tab=readme-ov-file#reference) cannot help here due the lack of a specific tag…

**Pull request merged**
