### PR TITLE
Add preset for natural arch

### PR DESCRIPTION
**Pull request by jake-low**
### Description, Motivation & Context

Adds a preset for [natural arches](https://en.wikipedia.org/wiki/Natural_arch), which applies the tag [`natural=arch`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Darch).

Natural arches are found all over the world. The tag `natural=arch` is the preferred way to tag them on OSM, but many are instead tagged as boulders (`natural=rock`) or tourist attractions (`tourism=attraction`). I believe this is mainly due to mappers not knowing that there is a specific tag for arches. Adding a preset will help make this tag more discoverable.
  
### Links and data

- [`natural=arch` on the OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Darch)
- [`natural=arch` on TagInfo](https://taginfo.openstreetmap.org/tags/natural=arch)

### Checklist and Test-Documentation Template

<details><summary>Read on to get your PR merged faster…</summary>

Follow these steps to test your PR yourself and make it a lot easier and faster for maintainers to check and approve it.

**This is how it works:**
1. After you submit your PR, the system will create a preview and comment on your PR:
   > 🍱 You can preview the tagging presets of this pull request here.
   If this is your first contribution to this project, the preview will not happen right away but requires a click from one of the project members. We will do this ASAP.

2. Once the preview is ready, use it to test your changes.

3. Now copy the snippet below into a new comment and fill out the blanks.

4. Now your PR is ready to be reviewed.

```
## Test-Documentation

### Preview links & Sidebar Screenshots

<!-- Use the preview to find examples, select the feature in question and **copy this link here**.
     Find examples of nodes/areas. Find examples with a lot of tags or very few tags. – Whatever helps to test this thoroughly.
     Add relevant **screenshots** of the sidebar of those examples. -->

<!-- FYI: What we will check:
     - Is the [icon](https://github.com/ideditor/schema-builder/blob/main/ICONS.md) well chosen.
     - Are the fields well-structured and have good labels.
     - Do the dropdowns (etc.) work well and show helpful data. -->

### Search

<!-- **Test the search** of your preset and share relevant **screenshots** here.
     - Test the preset name as search terms.
     - Also test the preset terms and aliases as search terms (if present). -->

### Info-`i`

<!-- **Test the info-i** for your fields and preset and share relevant **screenshots** here.
     The info needs to help mappers understand the preset and when to use it.
     [Learn more…](https://github.com/tordans/id-tagging-schema/blob/main/CONTRIBUTING.md#info-i)
 -->

### Wording

- [ ] American English
- [ ] `name`, `aliases` (if present) use Title Case
- [ ] `terms` (if present) use lower case, sorted A-Z
<!-- Learn more in https://github.com/openstreetmap/id-tagging-schema/blob/main/GUIDELINES.md#2-design-the-preset -->
```

</details>

### CODE REVIEW

**Comment by jake-low** [comment]
I tested my PR using the link above. It seems to be working except that the icon doesn't display. The referenced icon, `temaki-natural_arch`, is one I [recently added](https://github.com/rapideditor/temaki/pull/94) to Temaki. It's been released in the latest version of Temaki (v5.10.0). I looked in id-tagging-schema's `package.json` but the icon set dependencies aren't listed there, so I have some more learning to do about how the icons are included in this project. I'll look into this more when I have a bit of time.

**Comment by riQQ** [comment]
Temaki is in iD's package.json:
https://github.com/openstreetmap/iD/blob/develop/package.json#L82

**Comment by tordans** [comment]
Could you share the "Checklist and Test-Documentation Template" please. This will make reviewing faster.

**Comment by jake-low** [comment]
Sorry for the delayed reply. I'm working on getting iD bumped to use Temaki 5.10.0 so that the required icon for this preset is available. Once that's merged I will retest this PR (following the checklist) and post the results here.

**Comment by jake-low** [comment]
@tordans Are you able to approve the Github workflows for this PR? I pushed a new commit (iD now includes Temaki 5.10.0, I'm told) but it seems that someone needs to ok the CI run so that I can test the PR again. (I'll be sure to use the test checklist this time).

**Comment by tordans** [comment]
> Are you able to approve the Github workflows for this PR?

Just did, thanks for the ping. Once your first PR is merged this will happen automatically AFAIK.

**Comment by jake-low** [comment]
Okay, I finally had a chance to test this and fill out the requested documentation.

## Test-Documentation

### Preview links & Sidebar Screenshots

#### A `natural=arch` node with a small number of tags

https://pr-1352--ideditor-presets-preview.netlify.app/id/dist/#id=n1832397684&map=19.00/38.05174/-109.75652

image

#### A `natural=arch` multipolygon with many tags

https://pr-1352--ideditor-presets-preview.netlify.app/id/dist/#id=r14637765&map=19.00/38.74347/-109.49929

image

### Search

image image image

### Info-`i`

image

"View documentation" links to the [Tag:natural=arch wiki page](https://wiki.openstreetmap.org/wiki/Tag:natural=arch)

### Wording

- [x] American English
- [x] `name`, `aliases` (if present) use Title Case
- [x] `terms` (if present) use lower case, sorted A-Z

**Review by tordans — APPROVED** [review]

**Comment by tordans** [comment]
Thanks!

**Pull request merged**
