### PR TITLE
Reuse labels for `traffic_calming`

### LINKED ISSUE #1152: Duplicated entries in Transifex for `traffic_calming`
Almost every item from https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/traffic_calming.json is duplicated by it's standalone preset. Would it be possible to merge them? Ideally there would be an automated validation that warns when there are two strings with the same source text.

### PR DESCRIPTION
**Pull request by Dimitar5555**
Resolves #1152

Note: I haven't tested it which is why I've marked it as a draft.

### CODE REVIEW

**Comment by Dimitar5555** [comment]
It looks like it's not working. Will adding `presets/` in the beginning fix the problem?

image

**Comment by tordans** [comment]
@Dimitar5555 I think the way to do this is https://github.com/ideditor/schema-builder?tab=readme-ov-file#stringscrossreference
When I look through the code https://github.com/search?q=repo%3Aopenstreetmap%2Fid-tagging-schema+%22strings%22&type=code&p=2 I see cases like https://github.com/openstreetmap/id-tagging-schema/blob/87d7b90f93c822c879392466016c55b0e7932905/data/fields/crossing/markings_yes-PL.json#L14
But looking at https://github.com/search?q=repo%3Aopenstreetmap%2Fid-tagging-schema+%22options%22&type=code&p=5 there is no case that looks like what you are doing.

In general, this reference feature only works in very specific cases, not always.

**Comment by Dimitar5555** [comment]
`stringsCrossReference` is for the options in a field. It's not related to the field's label. Currently it's not possible to cross reference labels between presets and fields. This is a limitation of the schema builder.

Blocked by https://github.com/ideditor/schema-builder/issues/162

**Comment by tordans** [comment]
@Dimitar5555 thanks for opening the other issue. Can we close this PR until that is  resolved?

**Pull request closed without merging**
