### PR TITLE
remove downranking building=house entry

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by matkoniecz** [comment]
see https://github.com/openstreetmap/id-tagging-schema/issues/1155#issuecomment-2003768510

**Comment by matkoniecz** [comment]
Not sure why this downranking was added and what it solved.

**Comment by matkoniecz** [comment]
@DujaOSM It fixes what you reported but tracking down why downranking was added could be useful. Maybe there was a good reason for that?

**Comment by bhousel** [comment]
All buildings presets have `"matchScore": 0.5` and have had it for a long time.

This is because in OSM (unfortunately) buildings tags are often combined with more interesting tags, and the preset system is expected to match the more interesting tag.

For example `building=house`+`craft=plumber`

**Comment by DujaOSM** [comment]
Wow that was quick... 
For specifically residential buildings (house, detached, residential, apartments),  I don't see a reason to downgrade matchScore (much), since those are most commonly used standalone. However, apart from the name, I do not know how exactly matchScore is used: if it only affects string matching, I don't see why we would downgrade it when matching "hou" or "res"...

By the way, the common preset "residential area" also seems to suffer from the same disease...

**Comment by bhousel** [comment]
Off the top of my head, I don't know what will happen.
If you change the matchScores around without understanding what they do, you can probably expect some surprising preset matching behavior.

Yes, you might get "House" to rank higher on the list before "Houseware Store", but you wouldn't want "Church Building" match before "Church" or "Stadium Building" match before "Stadium".  The building tags are weird.

Maybe a better solution would be to prioritize shorter names in the preset list, but I don't know how that would affect different languages.

**Comment by matkoniecz** [comment]
As is it is not ready.

I will try to investigate more here (or in other iD preset area) once https://github.com/openstreetmap/id-tagging-schema/pulls/matkoniecz are processed

**Pull request closed without merging**
