### PR TITLE
adding additional values to Cuisine field

### PR DESCRIPTION
**Pull request by CornerSyrup**
Adding keys from [wiki](https://wiki.openstreetmap.org/wiki/Key:cuisine) to dictionary. Only coping those familiar and commonly used.

Changes:

- Add missing but common keys
- Sort to organise

### CODE REVIEW

**Comment by tyrasd** [comment]
would you mind summarizing which were the values you have newly added? It's hard to review because the sorting touched many of the existing options here.

> those familiar and commonly used.

how did you define this for this PR? For example: `izakaya` only has a few handful of uses in OSM right now… :thinking:

**Comment by tyrasd** [comment]
PS: the sorting seems a bit random at first glance. why not do it fully alphabetically if we're at it?

**Comment by matkoniecz** [comment]
@CornerSyrup Have you removed any values?

Can you maybe make PR that just adds missing values?

> how did you define this for this PR? For example: izakaya only has a few handful of uses in OSM right now… 🤔

It is also not documented at https://wiki.openstreetmap.org/wiki/Key:cuisine

If value is worth supporting in tagging presets it should be also documented at wiki (in my opinion)

It also helps people translating values.

Also, from https://en.wikipedia.org/wiki/Izakaya it seems not clear is it even a cuisine type.

**Comment by bryceco** [comment]
Here in the Seattle area the number of restaurants tagged as cuisine=izakaya is about the same as restaurants that are tagged as cuisine=japanese but include "Izakaya" in the name of the restaurant. Some of those restaurants have a name including "Ramen and Izakaya" or "Sushi and Izakaya". I think the lack of a preset is holding people back from tagging restaurants as the more precise izakaya rather than the more general japanese.

**Comment by tyrasd** [comment]
> removed any values

The only removed value is `coffee_shop`, which was replaced with `coffee`. This should be reverted, as `coffee_shop` has more than 100 times as many uses as `coffee`.

> `izakaya`

I would prefer to not discuss each and every value detail in this PR, as that would be a lot to go through. I only mentioned this one as a particular example which stood out to me as having particularly low usage.

In general, any value should be documented on the wiki, as a minimum in form of an entry on the value table of the respective key's page.

**Comment by tyrasd** [comment]
Back to the question which values we should include. Here's the current ranking of popularity of various cuisine values (taking into account multi-value tags with semicolon separated values): https://gist.github.com/tyrasd/aaa5d32cb05f8ed1acafdd2e40737254. Here's also a list comparing the values currently included and proposed in this PR:

| tag value | count | rank | wiki | before this PR | after this PR |
|---|---|---|---|---|---|
| `pizza` | 	151794 | 1 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `burger` | 	129511 | 2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `coffee_shop` | 	109597 | 3 | :heavy_check_mark: | :heavy_check_mark: | :x: |
| `regional` | 	106867 | 4 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `italian` | 	69823 | 5 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `sandwich` | 	69072 | 6 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `chinese` | 	59595 | 7 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `chicken` | 	48484 | 8 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `japanese` | 	37913 | 9 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `kebab` | 	35987 | 10 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `mexican` | 	35279 | 11 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `american` | 	33421 | 12 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `asian` | 	27756 | 13 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `ice_cream` | 	27402 | 14 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `indian` | 	26850 | 15 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `sushi` | 	25294 | 16 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `seafood` | 	21375 | 17 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `thai` | 	19154 | 18 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `french` | 	18885 | 19 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `german` | 	16069 | 20 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `breakfast` | 	15674 | 21 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `greek` | 	14881 | 22 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `steak_house` | 	14685 | 23 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `international` | 	14477 | 24 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `fish_and_chips` | 	13064 | 25 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `korean` | 	12325 | 26 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `barbecue` | 	12789 | 27 | :heavy_check_mark: | :x: (only as preset) | :heavy_check_mark: |
| `donut` | 	12108 | 28 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `local` | 	11837 | 29 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `noodle` | 	11211 | 30 | :heavy_check_mark: | :x: (only as preset) | :heavy_check_mark: |
| `vietnamese` | 	11048 | 31 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `fish` | 	10662 | 32 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `turkish` | 	10453 | 33 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `cake` | 	8967 | 34 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `pasta` | 	8894 | 35 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `tex-mex` | 	8737 | 36 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `bubble_tea` | 	8188 | 37 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `ramen` | 	7813 | 38 | :heavy_check_mark: | :x: (only as preset) | :heavy_check_mark: |
| `mediterranean` | 	6893 | 39 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `spanish` | 	6489 | 40 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `friture` | 	6478 | 41 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `tea` | 	6365 | 42 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `grill` | 	5968 | 43 |  | :x: | :x: |
| `juice` | 	5695 | 44 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `italian_pizza` | 	5234 | 45 | :x: (only as side note) | :x: | :x: |
| `salad` | 	5177 | 46 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `crepe` | 	4800 | 47 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `bakery` | 	4529 | 48 | :heavy_check_mark: (unclear if use is discouraged or not) | :x: | :x: |
| `hot_dog` | 	3962 | 49 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `pancake` | 	3958 | 50 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `dessert` | 	3483 | 51 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `diner` | 	3473 | 52 | :heavy_check_mark: | :x: | :x: |
| `tapas` | 	3465 | 53 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `coffee` | 	3187 | 54 | :x: (only as side note) | :x:| :heavy_check_mark: |
| `portuguese` | 	3114 | 55 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `beef_bowl` | 	2906 | 56 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `russian` | 	2806 | 57 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `indonesian` | 	2790 | 58 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `wings` | 	2706 | 59 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `lebanese` | 	2677 | 60 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `arab` | 	2630 | 61 | :heavy_check_mark: | :x: | :x: |
| `curry` | 	2472 | 62 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `malaysian` | 	2444 | 63 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `bagel` | 	2441 | 64 | :heavy_check_mark: | :x: | :x: |
| `noodles` | 	2377 | 65 | :x: (discouraged) | :x: | :x: |
| `steak` | 	2371 | 66 | :heavy_check_mark: (unclear if discouraged over `steak_house`) | :x: | :heavy_check_mark: |
| `georgian` | 	2171 | 67 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `polish` | 	2143 | 68 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `african` | 	2135 | 69 | :heavy_check_mark: | :x: | :x: |
| `western` | 	2088 | 70 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `sausage` | 	2064 | 71 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `filipino` | 	1988 | 72 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `caribbean` | 	1904 | 73 | :heavy_check_mark: | :x: | :x: |
| `soba` | 	1864 | 74 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `peruvian` | 	1814 | 75 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `brazilian` | 	1712 | 76 | :heavy_check_mark: | :x: | :x: |
| `oriental` | 	1633 | 77 | :heavy_check_mark: | :x: | :x: |
| `fine_dining` | 	1595 | 78 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `fast_food` | 	1450 | 79 | :heavy_check_mark: | :x: | :x: |
| `cafe` | 	1401 | 80 | :heavy_check_mark: | :x: | :x: |
| `dumplings` | 	1321 | 81 | :x: (discouraged over `dumpling`) | :x: | :x: |
| `frozen_yogurt` | 	1315 | 82 | :heavy_check_mark: | :x: | :x: |
| `argentinian` | 	1311 | 83 | :heavy_check_mark: | :x: | :x: |
| `buffet` | 	1291 | 85 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `balkan` | 	1267 | 86 | :heavy_check_mark: | :x: | :x: |
| `bavarian` | 	1251 | 87 | :heavy_check_mark: | :x: | :x: |
| `deli` | 	1225 | 88 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `shawarma` | 	1203 | 89 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `persian` | 	1160 | 90 | :heavy_check_mark: | :x: | :x: |
| `middle_eastern` | 	1147 | 91 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `pastry` | 	1147 | 92 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `buschenschank` | 	1123 | 93 | :heavy_check_mark: | :x: | :x: |
| `heuriger` | 	1092 | 94 | :heavy_check_mark: | :x: | :x: |
| `british` | 	1083 | 95 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `soup` | 	1058 | 96 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `fries` | 	1052 | 97 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `taiwanese` | 	1031 | 98 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| `bistro` | 	964 | 99 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `european` | 	948 | 100 | :heavy_check_mark: | :x:| :heavy_check_mark: |
| … (`moroccan`, `meat`) | | 101,102 | | :x: | :x: |
| `hawaiian` | 	875 | 103 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `brunch` | 	869 | 104 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `udon` | 	854 | 105 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … (`latin_american`, `lunch`) | | 106,107 | | :x: | :x: |
| `fried_chicken` | 	822 | 108 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`hotdog`) | | 109 | | :x: | :x: |
| `waffle` | 	808 | 110 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `hotpot` | 	796 | 111 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`poke`) | | 112 | | :x: | :x: |
| `fried_food` | 	774 | 113 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`pretzel`, `empanada`, `savory_pancakes`) | | 114…116 | | :x: | :x: |
| `falafel` | 	675 | 117 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`traditional`, `ethiopian`, `croatian`, `austrian`) | | 118…121 | | :x: | :x: |
| `chocolate` | 	635 | 122 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| …(`snack`) | | 123 | | :x: | :x: |
| `churro` | 	618 | 124 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`nepalese`, `irish`) | | 125,126 | | :x: | :x: |
| `pie` | 	580 | 127 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `smoothie` | 	574 | 128 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`pita`, `lao`, `barbeque`, `hungarian`, `pub`, `bolivian`) | | 129…134 | | :x: | :x: |
| `bar&grill` | 	513 | 135 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `cantonese` | 	506 | 136 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `gyros` | 	494 | 137 | :heavy_check_mark: |:x: | :heavy_check_mark: |
| `pakistani` | 	472 | 138 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `gyoza` | 	457 | 139 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`wine`, `piadina`) | | 140,141 | | :x: | :x: |
| `fusion` | 	431 | 142 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| …(`potato`, `beer`, `jamaican`) | | 143…145 | | :x: | :x: |
| `cuban` | 	404 | 146 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| `ukrainian` | 	388 | 147 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| …  | | 148…154 | | :x: | :x: |
| `yakiniku` | 	339 | 155 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 156…169 | | :x: | :x: |
| `swedish` | 	273 | 170 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 171,172 | | :x: | :x: |
| `mongolian_grill` | 	253 | 173 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 174…178 | | :x: | :x: |
| `couscous` | 	225 | 179 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 180…182 | | :x: | :x: |
| `yakitori` | 	217 | 183 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 184 | | :x: | :x: |
| `beef` | 	214 | 185 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 186…188 | | :x: | :x: |
| `dumpling` | 	207 | 189 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 190,191 | | :x: | :x: |
| `takoyaki` | 	197 | 192 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 193…213 | | :x: | :x: |
| `egyptian` | 	144 | 214 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 215…218 | | :x: | :x: |
| `jewish` | 	133 | 219 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 220…234 | | :x: | :x: |
| `mongolian` | 	119 | 235 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 236…287 | | :x: | :x: |
| `singaporean` | 	69 | 288 | :heavy_check_mark: | :x: | :heavy_check_mark: |
| … | | 289…415 | | :x: | :x: |
| `izakaya` | 	34 | 416 | :x: | :x: | :heavy_check_mark: |
| … | |  | | :x: | :x: |

**Comment by tyrasd** [comment]
Suggestion: let's start with completing the top-100 from the most popular values (excluding discouraged values of course). Maybe also skipping some hyper-local values like [`buschenschank`/`heuriger`](https://en.wikipedia.org/wiki/Heuriger) which are probably not really translatable into most languages.

**Pull request closed without merging**
