### PR TITLE
shot-put appears to be preferred

### PR DESCRIPTION
**Pull request by matkoniecz**
see https://wiki.openstreetmap.org/wiki/Tag:sport%3Dshot-put

thanks to https://www.openstreetmap.org/changeset/148005491 

note: untested, I will test once bot deploys it

### CODE REVIEW

**Comment by matkoniecz** [comment]
Seems that at least one other place needs to be changed to get sport label working

screen01
screen

**Review by tyrasd — DISMISSED** [review]

**Comment by matkoniecz** [comment]
Wait. There is https://wiki.openstreetmap.org/wiki/Tag:athletics%3Dshot_put but https://wiki.openstreetmap.org/wiki/Tag:sport%3Dshot-put

**Comment by matkoniecz** [comment]
So iD is right, though tagging situation is silly.

Maybe it is viable to get it better but that would not happen on this issue tracker.

**Comment by tyrasd** [comment]
yeah, was just about to write the same. It's quite confusing that the two values have different spelling, though. :see_no_evil: 

for reference, #817 added these presets

**Pull request closed without merging**
